=== netgroup-polito/verefoo/xsd/nfvSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--
 Copyright (c) 2017 Politecnico di Torino and others.
 All rights reserved. This program and the accompanying materials
 are made available under the terms of the Apache License, Version 2.0
 which accompanies this distribution, and is available at
 http://www.apache.org/licenses/LICENSE-2.0
-->
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    <xsd:include schemaLocation="errorSchema.xsd"/>
    <xsd:include schemaLocation="hateoasLinks.xsd"/>
    <xsd:include schemaLocation="xml_components.xsd"/>
	<xsd:element name="NFV">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="graphs" minOccurs="1" maxOccurs="1"/>
				<xsd:element ref="Constraints" minOccurs="0" maxOccurs="1"/>
				<xsd:element ref="PropertyDefinition" minOccurs="1" maxOccurs="1"/>
				<xsd:element ref="Hosts"/>
				<xsd:element ref="Connections"/>
				<xsd:element name="ParsingString" type="xsd:string" minOccurs="0" maxOccurs="1"/>
			</xsd:sequence>
		</xsd:complexType>		
	    <xsd:key name="hostKey">
	      <xsd:selector xpath="Hosts/Host" />
	      <xsd:field xpath="@name" />
	    </xsd:key>
	    <xsd:keyref name="ConnectionSourceHost" refer="hostKey">
	      <xsd:selector xpath="Connections/Connection" />
	      <xsd:field xpath="@sourceHost" />
	    </xsd:keyref>
	    <xsd:keyref name="ConnectionDestHost" refer="hostKey">
	      <xsd:selector xpath="Connections/Connection" />
	      <xsd:field xpath="@destHost" />
	    </xsd:keyref>
	    
	     <xsd:unique name="ConnectionUniqueness">
		    <xsd:selector xpath="Connections/Connection"/>
		    <xsd:field xpath="@sourceHost"/>
		    <xsd:field xpath="@destHost"/>
		</xsd:unique>
	    
	    
	    <xsd:keyref name="NodeMetricsRef" refer="keyNode">
	      <xsd:selector xpath="Constraints/NodeConstraints/NodeMetrics" />
	      <xsd:field xpath="@node" />
	    </xsd:keyref>
	    <xsd:keyref name="BandwidthSrcRef" refer="keyNode">
	      <xsd:selector xpath="Constraints/BandwidthConstraints/BandwidthMetrics" />
	      <xsd:field xpath="@src" />
	    </xsd:keyref>
	    <xsd:keyref name="BandwidthDstRef" refer="keyNode">
	      <xsd:selector xpath="Constraints/BandwidthConstraints/BandwidthMetrics" />
	      <xsd:field xpath="@dst" />
	    </xsd:keyref>
	    
	    <xsd:unique name="BandwidthUniqueness">
		    <xsd:selector xpath="Constraints/BandwidthConstraints/BandwidthMetrics"/>
		    <xsd:field xpath="@src"/>
		    <xsd:field xpath="@dst"/>
		</xsd:unique>
	    
	    <xsd:keyref name="fixedEndpointRef" refer="keyNode">
	      <xsd:selector xpath="Hosts/Host" />
	      <xsd:field xpath="@fixedEndpoint" />
	    </xsd:keyref>
	    <xsd:key name="keyGraph">
            <xsd:selector xpath="graphs/graph" />
            <xsd:field xpath="@id" />
        </xsd:key>
	    <xsd:keyref name="PropertyRef" refer="keyGraph">
	      <xsd:selector xpath="PropertyDefinition/Property" />
	      <xsd:field xpath="@graph" />
	    </xsd:keyref>
	</xsd:element>
	<xsd:element name="PropertyDefinition">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="Property" type="Property" maxOccurs="unbounded"/>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="Constraints">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="NodeConstraints" maxOccurs="1"/>
				<xsd:element ref="BandwidthConstraints" maxOccurs="1"/>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="NodeConstraints">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="NodeMetrics" minOccurs="0" maxOccurs="unbounded">
					<xsd:complexType>
			            <xsd:attribute name="node" type="xsd:string" use="required" />
			            <xsd:attribute name="nrOfOperations" type="xsd:long" use="optional"/>
			            <xsd:attribute name="maxNodeLatency" type="xsd:int" use="optional"/>
			            <xsd:attribute name="reqStorage" type="xsd:int" use="optional" default="0"/>
			            <xsd:attribute name="cores" type="xsd:int" use="optional" default="0"/>
			        </xsd:complexType>
       	 		</xsd:element>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="BandwidthConstraints">
		<xsd:complexType>
			<xsd:sequence>
       	 		<xsd:element name="BandwidthMetrics" minOccurs="0" maxOccurs="unbounded">
					<xsd:complexType>
			            <xsd:attribute name="src" type="xsd:string" use="required" />
			            <xsd:attribute name="dst" type="xsd:string" use="required" />
			            <xsd:attribute name="reqLatency" type="xsd:int" use="required"/>
			        </xsd:complexType>
       	 		</xsd:element>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="Hosts">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element minOccurs="0" maxOccurs="unbounded" ref="Host"/>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="Host">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="SupportedVNF" type="SupportedVNFType" maxOccurs="unbounded" minOccurs="0" />
				<xsd:element name="NodeRef" type="NodeRefType" maxOccurs="unbounded" minOccurs="0"/>
			</xsd:sequence>
			<xsd:attribute name="name" type="xsd:string" use="required"/>
			<xsd:attribute name="cpu" type="xsd:int" use="required"/>
			<xsd:attribute name="cores" type="xsd:int" use="required"/>
			<xsd:attribute name="diskStorage" type="xsd:int" use="required"/>
			<xsd:attribute name="maxVNF" type="xsd:int" use="optional"/>
			<xsd:attribute name="type" type="TypeOfHost" use="optional"/>
			<xsd:attribute name="fixedEndpoint" type="xsd:string" use="optional"/>
			<xsd:attribute name="active" type="xsd:boolean" use="optional" default="false"/>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="Connections">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="Connection" minOccurs="0" maxOccurs="unbounded"/>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="Connection">
		<xsd:complexType>
			<xsd:attribute name="sourceHost" type="xsd:string" use="required"/>
			<xsd:attribute name="destHost" type="xsd:string" use="required"/>
			<xsd:attribute name="avgLatency" type="xsd:int"/>
		</xsd:complexType>
		</xsd:element>
	<xsd:complexType name="NodeRefType">
		<xsd:attribute name="node" type="xsd:string" use="required"/>
	</xsd:complexType>
	<xsd:complexType name="SupportedVNFType">
		<xsd:attribute name="functional_type" type="functionalTypes" use="required" />
	</xsd:complexType>
	<xsd:simpleType name="TypeOfHost">
	    <xsd:restriction base="xsd:string">
	      <xsd:enumeration value="CLIENT"/>
	      <xsd:enumeration value="SERVER"/>
	      <xsd:enumeration value="MIDDLEBOX"/>
	 	</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="P-Name">
	    <xsd:restriction base="xsd:string">
	      <xsd:enumeration value="IsolationProperty"/>
	 	</xsd:restriction>
	</xsd:simpleType>
	<xsd:complexType name="Property">
				<xsd:attribute name="name" type="P-Name" use="required"/>
				<xsd:attribute name="graph" type="xsd:long" use="required"/>
				<xsd:attribute name="src" type="xsd:string" use="required"/>
				<xsd:attribute name="dst" type="xsd:string" use="required"/>
				<xsd:attribute name="isSat" type="xsd:boolean"/>
	</xsd:complexType>
</xsd:schema>

=== netgroup-polito/verefoo/testfile/AS.xml
<?xml version="1.0" encoding="UTF-8"?>
<NFV xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../xsd/nfvSchema.xsd">
  <graphs>
    <graph id="0">
     <node functional_type="WEBCLIENT" name="nodeA">
        <neighbour name="node1"/>
        <configuration description="A simple description" name="confA">
          <webclient nameWebServer="nodeB"/>
        </configuration>
      </node>
      <node functional_type="FIREWALL" name="node1">
        <neighbour name="nodeA"/>
        <neighbour name="node2"/>
        <configuration description="A simple description" name="conf1">
          <firewall>
            <elements>
              <source>nodeC</source>
              <destination>nodeD</destination>
            </elements>
          </firewall>
        </configuration>
      </node>
      <node functional_type="DPI" name="node2">
        <neighbour name="node1"/>
        <neighbour name="node3"/>
        <configuration description="A simple description" name="conf2">
          <dpi>
          	<notAllowed>nodeC</notAllowed>
          </dpi>
        </configuration>
      </node>
      <node functional_type="CACHE" name="node3">
        <neighbour name="node2"/>
        <neighbour name="node4"/>
        <configuration description="A simple description" name="conf3">
          <cache>
          	<resource>nodeA</resource>
          	<resource>node1</resource>
          	<resource>node2</resource>
          </cache>
        </configuration>
      </node>
	  <node functional_type="NAT" name="node4">
        <neighbour name="node3"/>
        <neighbour name="nodeB"/>
        <configuration description="A simple description" name="conf4">
         <nat>
          		<source>nodeA</source>
          		<source>node1</source>
          		<source>node2</source>
          		<source>node3</source>
          </nat>
        </configuration>
      </node>
   
      <node functional_type="WEBSERVER" name="nodeB">
        <neighbour name="node4"/>
        <configuration description="A simple description" name="confB">
          <webserver>
          	<name>nodeB</name>
          </webserver>
        </configuration>
      </node>
    </graph>
  </graphs>
  <Constraints>
	  <NodeConstraints>
			<NodeMetrics node="node1" reqStorage="38"/>
			<NodeMetrics node="node2" reqStorage="20"/>
			<NodeMetrics node="node3" reqStorage="50"/>
			<NodeMetrics node="node4" reqStorage="38"/>
	  </NodeConstraints>
	  <LinkConstraints/>
  </Constraints>
  <PropertyDefinition>
  		<Property graph="0" name="ReachabilityProperty" src="nodeA" dst="nodeB"/> 		
  </PropertyDefinition>
  <Hosts>
        <Host name="e050caaa" cpu="2" cores="2" memory="4" fixedEndpoint="nodeA" diskStorage="137" type="CLIENT"/>
        <Host name="5a01b700" cpu="4" cores="4" memory="16" maxVNF="4"  diskStorage="122" type="MIDDLEBOX">
			<SupportedVNF functional_type="FIREWALL"/>
			<SupportedVNF functional_type="CACHE"/>
			<SupportedVNF functional_type="ANTISPAM"/>
			<SupportedVNF functional_type="DPI"/>
			<SupportedVNF functional_type="NAT"/>
			<SupportedVNF functional_type="FIELDMODIFIER"/>
		</Host>
        <Host name="5a01b6ff" cpu="4" cores="4" memory="16" maxVNF="4" diskStorage="148" type="MIDDLEBOX">
			<SupportedVNF functional_type="FIREWALL"/>
			<SupportedVNF functional_type="CACHE"/>
			<SupportedVNF functional_type="ANTISPAM"/>
			<SupportedVNF functional_type="DPI"/>
			<SupportedVNF functional_type="NAT"/>
			<SupportedVNF functional_type="FIELDMODIFIER"/>
		</Host>
        <Host name="c0286ecd" cpu="4" cores="4" memory="16" maxVNF="4" diskStorage="106" type="MIDDLEBOX">
			<SupportedVNF functional_type="FIREWALL"/>
			<SupportedVNF functional_type="CACHE"/>
			<SupportedVNF functional_type="ANTISPAM"/>
			<SupportedVNF functional_type="DPI"/>
			<SupportedVNF functional_type="NAT"/>
			<SupportedVNF functional_type="FIELDMODIFIER"/>
		</Host>
        <Host name="c0286ece" cpu="4" cores="4" memory="16" maxVNF="4" diskStorage="147" type="MIDDLEBOX">
			<SupportedVNF functional_type="FIREWALL"/>
			<SupportedVNF functional_type="CACHE"/>
			<SupportedVNF functional_type="ANTISPAM"/>
			<SupportedVNF functional_type="DPI"/>
			<SupportedVNF functional_type="NAT"/>
			<SupportedVNF functional_type="FIELDMODIFIER"/>
		</Host>
        <Host name="e050ca8c" cpu="4" cores="4" memory="16" maxVNF="4" diskStorage="127" type="MIDDLEBOX">
			<SupportedVNF functional_type="FIREWALL"/>
			<SupportedVNF functional_type="CACHE"/>
			<SupportedVNF functional_type="ANTISPAM"/>
			<SupportedVNF functional_type="DPI"/>
			<SupportedVNF functional_type="NAT"/>
			<SupportedVNF functional_type="FIELDMODIFIER"/>
		</Host>
        <Host name="5a01b706" cpu="4" cores="4" memory="16" maxVNF="4" diskStorage="142" type="MIDDLEBOX">
			<SupportedVNF functional_type="FIREWALL"/>
			<SupportedVNF functional_type="CACHE"/>
			<SupportedVNF functional_type="ANTISPAM"/>
			<SupportedVNF functional_type="DPI"/>
			<SupportedVNF functional_type="NAT"/>
			<SupportedVNF functional_type="FIELDMODIFIER"/>
		</Host>
        <Host name="6f3cda8c" cpu="4" cores="4" memory="16" maxVNF="4" diskStorage="125" type="MIDDLEBOX">
			<SupportedVNF functional_type="FIREWALL"/>
			<SupportedVNF functional_type="CACHE"/>
			<SupportedVNF functional_type="ANTISPAM"/>
			<SupportedVNF functional_type="DPI"/>
			<SupportedVNF functional_type="NAT"/>
			<SupportedVNF functional_type="FIELDMODIFIER"/>
		</Host>
        <Host name="8951021b" cpu="4" cores="4" memory="16" maxVNF="4" diskStorage="143" type="MIDDLEBOX">
			<SupportedVNF functional_type="FIREWALL"/>
			<SupportedVNF functional_type="CACHE"/>
			<SupportedVNF functional_type="ANTISPAM"/>
			<SupportedVNF functional_type="DPI"/>
			<SupportedVNF functional_type="NAT"/>
			<SupportedVNF functional_type="FIELDMODIFIER"/>
		</Host>
        <Host name="fe24ec49" cpu="4" cores="4" memory="16" maxVNF="4" diskStorage="102" type="MIDDLEBOX">
			<SupportedVNF functional_type="FIREWALL"/>
			<SupportedVNF functional_type="CACHE"/>
			<SupportedVNF functional_type="ANTISPAM"/>
			<SupportedVNF functional_type="DPI"/>
			<SupportedVNF functional_type="NAT"/>
			<SupportedVNF functional_type="FIELDMODIFIER"/>
		</Host>
        <Host name="8951021c" cpu="4" cores="4" memory="16" maxVNF="4" diskStorage="127" type="MIDDLEBOX">
			<SupportedVNF functional_type="FIREWALL"/>
			<SupportedVNF functional_type="CACHE"/>
			<SupportedVNF functional_type="ANTISPAM"/>
			<SupportedVNF functional_type="DPI"/>
			<SupportedVNF functional_type="NAT"/>
			<SupportedVNF functional_type="FIELDMODIFIER"/>
		</Host>
        <Host name="e050ca8d" cpu="4" cores="4" memory="16" maxVNF="4" diskStorage="113" type="MIDDLEBOX">
			<SupportedVNF functional_type="FIREWALL"/>
			<SupportedVNF functional_type="CACHE"/>
			<SupportedVNF functional_type="ANTISPAM"/>
			<SupportedVNF functional_type="DPI"/>
			<SupportedVNF functional_type="NAT"/>
			<SupportedVNF functional_type="FIELDMODIFIER"/>
		</Host>
        <Host name="65d5058" cpu="4" cores="4" memory="16" maxVNF="4" diskStorage="110" type="MIDDLEBOX">
			<SupportedVNF functional_type="FIREWALL"/>
			<SupportedVNF functional_type="CACHE"/>
			<SupportedVNF functional_type="ANTISPAM"/>
			<SupportedVNF functional_type="DPI"/>
			<SupportedVNF functional_type="NAT"/>
			<SupportedVNF functional_type="FIELDMODIFIER"/>
		</Host>
        <Host name="65ade8e6" cpu="4" cores="4" memory="16" maxVNF="4" diskStorage="142" type="MIDDLEBOX">
			<SupportedVNF functional_type="FIREWALL"/>
			<SupportedVNF functional_type="CACHE"/>
			<SupportedVNF functional_type="ANTISPAM"/>
			<SupportedVNF functional_type="DPI"/>
			<SupportedVNF functional_type="NAT"/>
			<SupportedVNF functional_type="FIELDMODIFIER"/>
		</Host>
        <Host name="65d5057" cpu="4" cores="4" memory="16" maxVNF="4" diskStorage="133" type="MIDDLEBOX">
			<SupportedVNF functional_type="FIREWALL"/>
			<SupportedVNF functional_type="CACHE"/>
			<SupportedVNF functional_type="ANTISPAM"/>
			<SupportedVNF functional_type="DPI"/>
			<SupportedVNF functional_type="NAT"/>
			<SupportedVNF functional_type="FIELDMODIFIER"/>
		</Host>
        <Host name="65ade8e5" cpu="4" cores="4" memory="16" maxVNF="4" diskStorage="133" type="MIDDLEBOX">
			<SupportedVNF functional_type="FIREWALL"/>
			<SupportedVNF functional_type="CACHE"/>
			<SupportedVNF functional_type="ANTISPAM"/>
			<SupportedVNF functional_type="DPI"/>
			<SupportedVNF functional_type="NAT"/>
			<SupportedVNF functional_type="FIELDMODIFIER"/>
		</Host>
        <Host name="6f3cda68" cpu="4" cores="4" memory="16" maxVNF="4" diskStorage="147" type="MIDDLEBOX">
			<SupportedVNF functional_type="FIREWALL"/>
			<SupportedVNF functional_type="CACHE"/>
			<SupportedVNF functional_type="ANTISPAM"/>
			<SupportedVNF functional_type="DPI"/>
			<SupportedVNF functional_type="NAT"/>
			<SupportedVNF functional_type="FIELDMODIFIER"/>
		</Host>
        <Host name="c02871d5" cpu="4" cores="4" memory="16" maxVNF="4" diskStorage="136" type="MIDDLEBOX">
			<SupportedVNF functional_type="FIREWALL"/>
			<SupportedVNF functional_type="CACHE"/>
			<SupportedVNF functional_type="ANTISPAM"/>
			<SupportedVNF functional_type="DPI"/>
			<SupportedVNF functional_type="NAT"/>
			<SupportedVNF functional_type="FIELDMODIFIER"/>
		</Host>
        <Host name="e489dbc1" cpu="4" cores="4" memory="16" maxVNF="4" diskStorage="123" type="MIDDLEBOX">
			<SupportedVNF functional_type="FIREWALL"/>
			<SupportedVNF functional_type="CACHE"/>
			<SupportedVNF functional_type="ANTISPAM"/>
			<SupportedVNF functional_type="DPI"/>
			<SupportedVNF functional_type="NAT"/>
			<SupportedVNF functional_type="FIELDMODIFIER"/>
		</Host>
        <Host name="2d720ca9" cpu="4" cores="4" memory="16" maxVNF="4" diskStorage="125" type="MIDDLEBOX">
			<SupportedVNF functional_type="FIREWALL"/>
			<SupportedVNF functional_type="CACHE"/>
			<SupportedVNF functional_type="ANTISPAM"/>
			<SupportedVNF functional_type="DPI"/>
